### ISSUE TITLE
Fail in making of manual of booth.

### ISSUE THREAD

**Issue by yuusuke** [jjzhang/booth#13]
I compiled booth in the environment where help2man was in.
However, I fail in making of manual of booth by the following errors.

# make
[snip]
make[2]: **\* No rule to make target `booth.8', needed by`all-am'.  Stop.
make[2]: Leaving directory `/root/github/booth/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory`/root/github/booth/src'
make: **\* [all-recursive] Error 1

**Comment by aspiers** [comment]
Yes, I can reproduce this if help2man is installed.  This is clearly due to `src/Makefile.am`:

``` make
if HAVE_HELP2MAN
man_MANS        = booth.8 boothd.8
MAINTAINERCLEANFILES    += $(man_MANS)
EXTRA_DIST      = $(man_MANS)

%.8: %
    $(HELP2MAN) -N -o $@ ./$<
endif
```

I suspect it was deliberately left in there to remind someone that the correct fix is to write a man page ;-)  Currently the repo does not contain one.  I have filed a [new bugzilla entry](https://bugzilla.novell.com/show_bug.cgi?id=753276) to track this downstream.

**Comment by yuusuke** [comment]
I confirmed that it was revised.
Thanks!
